version: 0.2

phases:
  build:
    commands:
      - echo Build Phase
      - cd ./Pokemon-Project-Frontend/
      - npm install
      - npm run build
  post_build:
    commands:
      - echo PostBuild Phase
artifacts:
  files:
    - '**/*'
  base-directory: dist
